---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /Users/{{ ansible_user_id }}/.oh-my-zsh
  - role: osxc.repository
    clone_url: https://github.com/square/maximum-awesome.git
    dest: /Users/{{ ansible_user_id }}/.vim
    links:
    - src: vimrc
      dest: /Users/{{ ansible_user_id }}/.vimrc
    - src: vimrc.bundles
      dest: /Users/{{ ansible_user_id }}/.vimrc.bundles
    - src: tmux.conf
      dest: /Users/{{ ansible_user_id }}/.tmux.conf
  - role: osxc.repository
    clone_url: https://github.com/gmarik/vundle.git
    dest: /Users/{{ ansible_user_id }}/.vim/bundle/vundle
  - role: osxc.repository
    clone_url: https://github.com/dai0304/dotfiles.git
    dest: /Users/{{ ansible_user_id }}/.dotfiles
    links:
    - src: gitconfig
      dest: /Users/{{ ansible_user_id }}/.gitconfig
    - src: gitignore
      dest: /Users/{{ ansible_user_id }}/.gitignore
    - src: tmux.conf.local
      dest: /Users/{{ ansible_user_id }}/.tmux.conf.local
    - src: vimrc.bundles.local
      dest: /Users/{{ ansible_user_id }}/.vimrc.bundles.local
    - src: vimrc.local
      dest: /Users/{{ ansible_user_id }}/.vimrc.local
    - src: zshrc
      dest: /Users/{{ ansible_user_id }}/.zshrc
  - role: osxc.repository
    clone_url: https://github.com/riywo/anyenv
    dest: /Users/{{ ansible_user_id }}/.anyenv
  tasks:
  - name: enable mysql startup
    command: ln -sfv {{ item }} /Users/{{ ansible_user_id }}/Library/LaunchAgents
    with_fileglob:
    - /usr/local/opt/mysql/*.plist
#  - name: setup anyenv
#    command: /Users/{{ ansible_user_id }}/.anyenv/bin/anyenv install {{ item }}
#    with_items:
#    - rbenv
  post_tasks:
  - copy: src=oh-my-zsh/custom dest=/Users/{{ ansible_user_id }}/.oh-my-zsh backup=yes

- hosts: all
  roles:
  - osxc.common-env
